---
- name: Include Check VM task
  ansible.builtin.include_tasks: check_vm_disk.yaml
  when: check_disk == "True"

- name: Include Add Disk task
  ansible.builtin.include_tasks: add_vm_disk.yaml
  when: add_disk == "True"

#- name: Include Cloud-Init task  
#  ansible.builtin.include_tasks: cloud_init.yaml
#  when: cloud_init == "True" and add_disk_result.changed 
